name: RustDesk Windows VM

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install RustDesk
        run: |
          choco install rustdesk -y

      - name: Show RustDesk ID and Password
        run: |
          type "C:\Program Files\RustDesk\id.txt"
          type "C:\Program Files\RustDesk\passwd.txt"
          Start-Sleep -Seconds 21600
